### ISSUE TITLE
Can we visualize the result during training?

### ISSUE THREAD

**Issue by Michaelwhite34** [yashbhalgat/HashNeRF-pytorch#12]
For now there is only current training step.

**Comment by YtengTan** [comment]
Hi, the code has a testset visualization option if you check "run_nerf.py" line 577, the default setting is every 1k iterations.

**Comment by yashbhalgat** [comment]
You can use `i_testset` option to visualize your results on the testset (during training). There's also a `i_video` option that you can have a look at.
