### ISSUE TITLE
Trained weights for forward facing scene

### ISSUE THREAD

**Issue by SrinjaySarkar** [yashbhalgat/HashNeRF-pytorch#13]
Hello Yash,
Thank you very much for the Pytorch port. Could you please share the trained weight file for any of the forward facing datasets?

**Comment by yashbhalgat** [comment]
Hi @SrinjaySarkar, I have now uploaded few of the trained checkpoints here: https://drive.google.com/drive/folders/1E0lDPeoPfSLe4aafkohZgpl2EyL8tsnA?usp=sharing
Let me know if you have any issues using these. :)

**Comment by SrinjaySarkar** [comment]
Hi @yashbhalgat  thank you very much for the weight files.  I have 2 questions based on that
1: I found the value for the `weights["network_fine_state_dict"]` to be non empty for the fern dataset. However, the default value of `N_importance` is 0. Did you add the resampled fine points? If so how many? 64?

2:During training you didn't add the parameters of the view direction embedding network to the optimizer [here](https://github.com/yashbhalgat/HashNeRF-pytorch/blob/main/run_nerf.py#:~:text=optimizer%20%3D%20RAdam(%5B,betas%3D(0.9%2C%200.99))) . Is this because you are using SH for view directions ?

**Comment by yashbhalgat** [comment]
Yes, I am using SH for viewing directions (as also mentioned in the original Instant-NGP paper). SH encoding doesn't have any trainable parameters.
