### ISSUE TITLE
How to train on our own data?

### ISSUE THREAD

**Issue by zjz123-eng** [yashbhalgat/HashNeRF-pytorch#17]
Hello, I would like to train on my own dataset. Is the repo able to do that?

**Comment by lixinghe1999** [comment]
seems you need to go to the Nvidia official repo and use ColMap to generate the transform.json, which makes your dataset aligned to the provided ones.

**Comment by jjparkcv** [comment]
May I ask what do you do after you get the transform.json file?

**Comment by yashbhalgat** [comment]
Once you get the transforms.json file, you can follow the [load_blender.py](https://github.com/yashbhalgat/HashNeRF-pytorch/blob/main/load_blender.py) script to write a dataloader for your own dataset.

**Comment by omnipotenttom** [comment]
> 获取transforms.json文件后，可以按照 [load_blender.py](https://github.com/yashbhalgat/HashNeRF-pytorch/blob/main/load_blender.py) 脚本为自己的数据集编写数据加载器。

why does my own dataset performs not well? I used colmap to make the dataset,and revised the  loadblender.py. What'more, the PSNR reamains at 30+during training while the render video seems bad.
