### ISSUE TITLE
some errors in code

### ISSUE THREAD

**Issue by taoranyi** [yashbhalgat/HashNeRF-pytorch#2]
File "/data/ytr/conda/envs/direct/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/ytr/HashNeRF-pytorch/hash_encoding.py", line 63, in forward
    voxel_min_vertex, voxel_max_vertex, hashed_voxel_indices = get_voxel_vertices(\
  File "/data/ytr/HashNeRF-pytorch/utils.py", line 83, in get_voxel_vertices
    hashed_voxel_indices = hash(voxel_indices, log2_hashmap_size)
  File "/data/ytr/HashNeRF-pytorch/utils.py", line 18, in hash
    return ((1<<log2_hashmap_size)-1) & (x*73856093 ^ y*19349663 ^ z*83492791)
TypeError: unsupported operand type(s) for &: 'int' and 'Tensor'

Can you tell me how to solve it?

**Comment by walsvid** [comment]
Hi, @taoranyi. For higher version PyTorch you can wrap a **Tensor** around the **int**.
```python
return torch.tensor((1<<log2_hashmap_size)-1) & (x73856093 ^ y19349663 ^ z83492791)
```

**Comment by yashbhalgat** [comment]
Hmm, that's strange. I am able to reproduce close to 33.5 PSNR in 5k iterations. What hyperparameters have you used? @taoranyi

**Comment by taoranyi** [comment]
@yashbhalgat default config in the code 
Command is 
python run_nerf.py --config configs/lego.txt --finest_res 512 --log2_hashmap_size 19 --lrate 0.01 --lrate_decay 10

**Comment by yashbhalgat** [comment]
@taoranyi @walsvid thanks for pointing this out! Let's shift this conversation to the #4. I will close this issue now.
