### ISSUE TITLE
Training is very slow.

### ISSUE THREAD

**Issue by LaolangOne** [yashbhalgat/HashNeRF-pytorch#22]
After training for just 5k iterations (~10 minutes on a single 1050Ti), you start seeing a crisp chair rendering. :).But I trained 5000 times on Tesla M60 6G, which took about an hour in total.Can you help me?

**Comment by Chenbinbin-T** [comment]
I had the same problem，it slower than the original nerf

**Comment by Chenbinbin-T** [comment]
I use RTX3090 to train HashNeRF

**Comment by yashbhalgat** [comment]
> After training for just 5k iterations (~10 minutes on a single 1050Ti), you start seeing a crisp chair rendering. :).But I trained 5000 times on Tesla M60 6G, which took about an hour in total.Can you help me?

This looks like a GPU issue, not an issue with the implementation. For more information on the training speed of this implementation, please refer https://github.com/yashbhalgat/HashNeRF-pytorch/issues/4#issuecomment-1144708129.
