### ISSUE TITLE
Training speed and training effect

### ISSUE THREAD

**Issue by mowangmodi** [yashbhalgat/HashNeRF-pytorch#23]
I feel that the training speed is very slow, which is not as good as NERF, and the effect is not very good? What is the situation?

**Comment by yashbhalgat** [comment]
Hi, the training speed aspect has been explained here: https://github.com/yashbhalgat/HashNeRF-pytorch/issues/4#issuecomment-1144708129

Can you explain what you mean by "effect is not very good"?

**Comment by mowangmodi** [comment]
This pure pytorch（python） implementation has the same training speed as nerf (pytorch), but pure pytorch（python） converges quickly. Am I right?

**Comment by yashbhalgat** [comment]
Yes.
