### ISSUE TITLE
Another PyTorch only NGP implementation

### ISSUE THREAD

**Issue by cheind** [yashbhalgat/HashNeRF-pytorch#26]
Hey there,

I've recently come across your work on NGP via an issue at the official instant-ngp. Great work! 

I am working on a very similar project. I have added acceleration structures and dynamic background training in spirit (but not exactly the same) of instant-ngp, however my PSNR results are constantly below the values reported by ngp (on synthetic data: 27dB vs 35dB). Did you experience  similar issues?

Here's my repo in case you want to browse it:
https://github.com/cheind/pure-torch-ngp

**Comment by yashbhalgat** [comment]
Yes, this is being discussed here: https://github.com/yashbhalgat/HashNeRF-pytorch/issues/4
