### ISSUE TITLE
About the size of the hash table

### ISSUE THREAD

**Issue by CongSuxu** [yashbhalgat/HashNeRF-pytorch#31]
I observed that the size of the hash table for each resolution level is fixed at 2^19, but when the resolution is 512, the number of voxels should be 512^3, which has exceeded the hash table of this level size, may I ask how so many voxels are put into the hash table?

**Comment by yashbhalgat** [comment]
There will be hash collisions. Although, there are multiple resolutions of voxel grids stacked together. So, for a query position `x`, the probability that a hash collision occurs in every grid at **every** resolution is very small. So, the overall concatenated embedding is unlikely to have any collisions.
