### ISSUE TITLE
"coarse and fine network"?

### ISSUE THREAD

**Issue by Misaliet** [yashbhalgat/HashNeRF-pytorch#33]
Hi,

I have take a look at your code and the original instant-ngp code, it seems there is a difference about coarse and fine network.
I'm not sure if my understanding is correct, so I want to ask and make sure.

The corse and fine network structures in the original nerf do not seem to be used in the instant-ngp. The instant-ngp uses "Occupancy Grids" (Appendix E.2) to sample points to avoid sampling points at empty positions.
Your code here is handled differently from instant-ngp, is this understanding correct?

Cheers,
Light

**Comment by yashbhalgat** [comment]
Hi @Misaliet, yes, that's correct.
