### ISSUE TITLE
Tiny-cuda-nn bindings

### ISSUE THREAD

**Issue by danperazzo** [yashbhalgat/HashNeRF-pytorch#5]
Hello, thank you for releasing this really usefull code! I have been wondering if you and your team have done any test (or think of any integration) with the [tiny-cuda-nn bindings](https://github.com/NVlabs/tiny-cuda-nn) already released by NVIDIA. And if, maybe, it could speed-up performance.

**Comment by ashawkey** [comment]
Maybe you can check [torch-ngp](https://github.com/ashawkey/torch-ngp) for CUDA bindings.

**Comment by yashbhalgat** [comment]
As mentioned above, @ashawkey has an excellent implementation [here](https://github.com/ashawkey/torch-ngp) with tiny-cuda-nn bindings. :)
