### ISSUE TITLE
The meaning behind the hash function params and their difference from paper?

### ISSUE THREAD

**Issue by Guptajakala** [yashbhalgat/HashNeRF-pytorch#6]
Hi, I noticed the hashing is different from the paper, and the prime numbers are also different from the paper. Could you explain what's the meaning of your implementation and the design choice?
`torch.tensor((1<<log2_hashmap_size)-1) & (x*73856093 ^ y*19349663 ^ z*83492791)`

**Comment by yashbhalgat** [comment]
@Guptajakala nice observation! Actually, I had borrowed these prime numbers from the open source implementation of [Instant-NGP](https://github.com/NVlabs/instant-ngp). Seems like the authors have updated the hash function. I have made the corresponding changes and pushed it to the repo now.

New hash function:
```
def hash(coords, log2_hashmap_size):
    '''
    coords: this function can process upto 7 dim coordinates
    log2T:  logarithm of T w.r.t 2
    '''
    primes = [1, 2654435761, 805459861, 3674653429, 2097192037, 1434869437, 2165219737]

    xor_result = torch.zeros_like(coords)[..., 0]
    for i in range(coords.shape[-1]):
        xor_result ^= coords[..., i]*primes[i]

    return torch.tensor((1<<log2_hashmap_size)-1).to(xor_result.device) & xor_result
```
