### ISSUE TITLE
Can the checkpoint be loaded in instant-ngp's viewer (or any interactive viewer) ? 

### ISSUE THREAD

**Issue by amanshenoy** [yashbhalgat/HashNeRF-pytorch#8]
Hey, Great work on the repo! 

Just wanted to ask if there is any straightforward way to load the checkpoint into the original instant-ngp viewer? or if there are any recommendations for generating novel views as one controllably moves around the scene.

**Comment by yashbhalgat** [comment]
@amanshenoy, thank you!
Haven't really looked into Instant-NGP viewer integration, but that would indeed be a nice addition.
For now, you can see that the *spiraling* poses are defined in the dataloaders, like here: https://github.com/yashbhalgat/HashNeRF-pytorch/blob/a7d64eeb8844b57f5ba90463185a1506e2cbb4b8/load_blender.py#L76
